{
  imports = [
    ./alacritty.nix
    ./bat.nix
    ./eza.nix
    ./git.nix
    ./hyprland.nix
    ./lazygit.nix
    ./quickshell.nix
    ./ranger.nix
    ./rofi.nix
    ./rust.nix
    ./stylix.nix
    ./udiskie.nix
    ./waybar.nix
    ./wlogout.nix
    ./zathura.nix
    ./zsh.nix
    ./nushell.nix
    ./neovim.nix
  ];
}
