{ config, pkgs, inputs, ... }: {
  imports = [
    ./hyprland/monitor.nix
    ./hyprland/keybinds.nix
    ./hyprland/keyboard.nix
    ./hyprland/scripts.nix
    ./hyprland/hyprlock.nix
    ./hyprland/hypridle.nix
  ];

  home.packages = with pkgs; [
    hyprlock
    hypridle
  ];
  
  wayland.windowManager.hyprland = {
    enable = true;
    package = inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system}.hyprland;
    portalPackage = inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system}.xdg-desktop-portal-hyprland;

    settings = {
      autogenerated = 0;
    };
  };
}
