{ config, pkgs, inputs, ... }: {
  imports = [
    ./hyprland/monitor.nix
    ./hyprland/keybinds.nix
    ./hyprland/keyboard.nix
    ./hyprland/scripts.nix
    ./hyprland/hyprlock.nix
    ./hyprland/hypridle.nix
  ];

  home.packages = with pkgs; [
    hyprlock
    hypridle
  ];
  
  wayland.windowManager.hyprland = {
    enable = true;
    package = inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system}.hyprland;
    portalPackage = inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system}.xdg-desktop-portal-hyprland;

    plugins = [
      inputs.split-monitor-workspaces.packages.${pkgs.stdenv.hostPlatform.system}.split-monitor-workspaces
    ];

    settings = {
      autogenerated = 0;
      "plugin:split-monitor-workspaces" = {
        count = 5;
        enable_wrapping = 0;
      };
    };
  };
}
