{
  imports = [
    ./audio.nix
    ./battery.nix
    ./bluetooth.nix
    ./env.nix
    ./fingerprint.nix
    ./home-manager.nix
    ./kernel.nix
    ./keyboard.nix
    ./locales.nix
    ./mime.nix
    ./polkit.nix
    ./ssh.nix
    ./stylix.nix
    ./net.nix
    ./nh.nix
    ./nix.nix
    ./pam.nix
    ./timezone.nix
    ./user.nix
    ./wm.nix
    ./zram.nix
  ];
}
